name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '0 */10 * * *'   # Every 10 hours
  workflow_dispatch:          # Allow manual run

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Streamlit app
        run: |
          curl -s https://your-app-name.streamlit.app > /dev/null || echo "Ping failed"
