name: Scheduled Empty Commit

on:
  schedule:
    - cron: '0 */8 * * *'  # Every 8 hours (more frequent)
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Keep alive commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main
          git commit --allow-empty -m "Keep alive: $(date)"
          git push origin main
